AliceO2Group/Run3AnalysisValidation

- codeHF/runtest_new.sh
- Adjust runtest_new.sh to the new options implemented in ComputeVerticesRun1.C
> Fix runtest configuration

- codeHF/Compare.C
- codeHF/ComputeVerticesRun1.C
- codeHF/runtest_new.sh
- include rejection of LS pairs (as in Run3) 
- add primary vertex position plots
- add option to select the mass windows of the invariant mass spectrum
> Include LS pair reject + primary vertex histograms 

- update_alio2.sh
This script performs a complete update of an AliPhysics + O2 installation.
It updates the local and remote repositories, builds the current branches of AliPhysics and O2 and removes obsolete builds.
> Add a script for fully automatic updating of repositories and builds.

- update_alio2.sh
Update all branches by the same function.
Update from fork first to allow for cross-machine syncing.
Take care of preserving uncommitted local changes via stash.
Improve logging and documentation.
> Improve the updating script.

- codeHF/ComputeVerticesRun1.C
- codeHF/dpl-config_std.json
To be merged after https://github.com/AliceO2Group/AliceO2/pull/4509
> adding prefiltering cut on the 2 and 3 prong candidate minimum pt

- codeHF/config_input.sh
@mmazzilli @njacazio please confirm this production is the right one to look at
> Add scenario2 for Run5 dataset

- README.md
- codeHF/Compare.C
- codeHF/RunHFTaskLocal.C
- codeHF/config_input.sh
- codeHF/config_tasks.sh
- exec/batch_ali.sh
- exec/batch_convert.sh
- exec/batch_o2.sh
- exec/run_ali.sh
- exec/run_convert.sh
- exec/run_o2.sh
- exec/runtest.sh
- exec/update_packages.sh
- exec/utilities.sh
- Add support for multiple input files per job (conversion, AliPhysics, O2).
- Show number of jobs.
- Show job progress in debug mode.
- Reduced copying of files.
- Show warnings and errors in the main log files and report in the terminal.
- More protection.
- Documentation extended, more explicit and clearer.
- Improve updating script.
> Framework optimisation and improvement.

- codeHF/Compare.C
- codeHF/config_tasks.sh
- exec/runtest.sh
- Simplify adding of new histograms and canvases and their manipulation.
- Allow for more flexible settings per histogram and canvas.
> Rework comparison macro.

- codeHF/Compare.C
Remove plots already present in other canvases.
> Dplus: Remove redundant plots

- codeHF/PlotEfficiency.C
- codeHF/clean.sh
- codeHF/config_tasks.sh
The PlotEfficiency.C macro now loops over particles provided in a string.
> Generalise efficiency plotting.

- codeHF/dpl-config_run3.json
- codeHF/dpl-config_run5.json
To be merged together with:
https://github.com/AliceO2Group/AliceO2/pull/5393
> Replace the eta cut on the candidate with the Y cut n the json files

- .github/workflows/superlinter.yml
This will make the tests a bit faster and the logs shorter and cleaner.
> Super-lint only new and changed files.

- FirstAnalysis/HFmcvalidation.py
Python Macro to plot HFMC Validation results
> PWGHF: Macro to plot HFMC Validation results

- FirstAnalysis/trackingstudies.py
Some changes for tracking  QA script
> Update tracking QA script

- codeHF/config_tasks.sh
- codeHF/dpl-config_run3.json
- codeHF/dpl-config_run5.json
@ginnocen @vkucera @nzardosh Here I updated the code to add the Dplus selections and efficiency. I also fixed a bug introduced by some modifications of the AliPhysics task.
> Add D+ selector

- codeHF/Compare.C
This is part of the alignment of vertex histograms between O2 and AliPhysics
> Update 3-prong vertex histo names

- codeHF/config_tasks.sh
- codeHF/dpl-config_run3.json
- codeHF/dpl-config_run5.json
This simply adds the X task to the config_task.sh
Edit: The corresponding PR in O2: AliceO2Group/AliceO2#5469
> Add X task.

- codeHF/config_tasks.sh
TaskName inserted in taskXic.cxx in o2
> Restore efficiency calculation for Xic

- FirstAnalysis/plotSigVsBkg.py
This is a python macro I wrote to create signal vs background plots for all pT bins of a candidate
> Add macro for signal vs background plots

- FirstAnalysis/distrib_studies.py
First use case of HFPlot for distrib_studies.py
See https://github.com/benedikt-voelkel/HFPlot
> Use HFPlot

- FirstAnalysis/database.yaml
path to results still needed
also fixed a typo in the Xi_cc histo list
> add X(3872) to yaml database

- codeHF/RunHFTaskLocal.C
Related PR: https://github.com/alisw/AliPhysics/pull/17964
> Propagate MC switch in the AliPhysics task

- codeHF/config_tasks.sh
- codeHF/workflows.yml
Add configuration to config_tasks.sh and workflows.yml for running X tree creator task
> PWGHF: Add configuration for running X tree creator task

- codeHF/config_tasks.sh
- codeHF/workflows.yml
related PR : https://github.com/AliceO2Group/O2Physics/pull/56
> Add Ξcc tree creator workflow

- FirstAnalysis/sig_vs_bkg.py
This should fix some issues with automatic plotting range on the y axis.
> Improve the sig_vs_bkg plotting script

- codeHF/config_tasks.sh
- codeHF/dpl-config_run3.json
- codeHF/dpl-config_run5_hf.json
- codeHF/dpl-config_run5_oniaX.json
- codeHF/workflows.yml
Related PR: https://github.com/AliceO2Group/O2Physics/pull/94
> Add primary-vertex selection in skimming

- codeHF/workflows.yml
In connection to PR in O2Physics: https://github.com/AliceO2Group/O2Physics/pull/164
> PWGHF: changed lc task from centrality selection to multiplicity counting

- codeHF/dpl-config_run3.json
Update Xic configuration
O2Physics: https://github.com/AliceO2Group/O2Physics/pull/1012
> PWGHF: Update Xic configuration

- codeHF/dpl-config_run3.json
Process switches need to be updated based on this PR: https://github.com/AliceO2Group/O2Physics/pull/1159
> PWGHF: split process functions

- codeHF/dpl-config_run3.json
Related PR in O2Physics: [#1393](https://github.com/AliceO2Group/O2Physics/pull/1393)
> Add isRun2 flag for B field setting from CCDB.

- codeHF/dpl-config_run3.json
- codeHF/workflows.yml
related PR: https://github.com/AliceO2Group/O2Physics/pull/1513
> PWGHF: updated PID parameters in candidate-selector-lc-to-k0s-p

- codeHF/dpl-config_run3.json
Related to [PR1564](https://github.com/AliceO2Group/O2Physics/pull/1564)
> B+ creator: ProcessSwitch

- codeHF/dpl-config_run3.json
- codeHF/workflows.yml
changes related to https://github.com/AliceO2Group/O2Physics/pull/1815
not sure about how to propagate these changes into workflows.yml. Now I just removed `"options: --doCascades"`, not sure if this is all that needs to be done?
> PWGHF: updated hf-track-index-skim-creator-cascades with process_switch

- codeHF/dpl-config_run3.json
changes related to https://github.com/AliceO2Group/O2Physics/pull/1900
> PWGHF: process_switch in hf-track-index-skim-creator

- codeHF/dpl-config_run3.json
changes related to https://github.com/AliceO2Group/O2Physics/pull/1921
> PWGHF: B field from ccdb in candidateCreatorCascade

- codeHF/dpl-config_run3.json
changes related to https://github.com/AliceO2Group/O2Physics/pull/2141
> PWGHF: updated PID in candidateSelectorLcToK0sP

- codeHF/dpl-config_run3.json
- codeHF/workflows.yml
Related PR: https://github.com/AliceO2Group/O2Physics/pull/2237
> Update track-to-collision association workflow

- .gitignore
- codeHF/Compare.C
Needs https://github.com/AliceO2Group/O2Physics/pull/2325 and https://github.com/alisw/AliPhysics/pull/22014
> Add comparison plots for Ds

- .isort.cfg
- .mega-linter.yml
- .ruff.toml
- FirstAnalysis/homogenize_output.py
- codeHF/compare.py
- codeHF/config_tasks.sh
- codeHF/dpl-config_run3.json
- codeHF/workflows.yml
- exec/download_from_grid.sh
- exec/runtest.sh
- pyproject.toml
- pyrightconfig.json
- Improve compare script
- Limit number of downloading jobs
- Add option to select AliPhysics and O2Physics branches.
- Save resources monitoring data.
- Add new correlation workflows.
- Fix dependencies.
- Fix candidate creator executables.
- Update linters configuration files
> Fix, update and improve configuration and scripts

- codeHF/dpl-config_run3.json
Requires https://github.com/AliceO2Group/O2Physics/pull/3046
> Add KFParticle to D0 creator

- codeHF/config_input.sh
Hi @vkucera, this adds the possibility to run on newer MC.
> New MCs in config_input

- codeHF/dpl-config_run3.json
Adding configurables introduced in https://github.com/AliceO2Group/O2Physics/pull/3939
> Add configurables for proton PID in skimming

- codeJE/Compare.C
Renamed collision vertex histogram to a more standard name in AliPhysics task
here is the corresponding AliPhysics PR https://github.com/alisw/AliPhysics/pull/22995
> renamed VtxZ histogram

- FirstAnalysis/hf_analysis_utils.py
- FirstAnalysis/hf_pt_spectrum.py
Follow-up to https://github.com/AliceO2Group/Run3Analysisvalidation/pull/439
> Fix hf_pt_spectrum script

- codeJE/dpl-config.json
Since someone decided to rename the hybridTracksJE to hybridTracks, we need to update this in our config file as well.
> Updating trackselection

- codeHF/config_tasks.sh
- codeHF/dpl-config_run3.json
- codeHF/workflows.yml
- config/workflows_dummy.yml
FYI @pstahlhu @creetz16 @JaeYoonCHO
> Add Ξc+ → Ξ π π workflows. Update TPC. Update Lc selector.

- exec/run_o2.sh
> Remove timing command
